name: CommandsPlugin2
version: '${project.version}'
main: me.shadow_warrior_.commandsplugin2.CommandsPlugin2
api-version: 1.16
authors: [ shadow_warrior_ ]
description: Commands in different classes
commands:
  god:
    description: Become invincible
    usage: /<command>
    aliases:
      - g
  feed:
    description: Feeding
    usage: /<command>
  repeat:
    description: Repeating your input
    usage: /<command> <message>
  psm:
    description: BLocking targets from moving
    usage: /<command> <player>